-- Phase 1: user profiles, courses, enrollments, and role-based access.

create type public.app_role as enum ('student', 'instructor', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role public.app_role not null default 'student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.courses (
  id bigint generated by default as identity primary key,
  code text not null unique check (code in ('ITN', 'SRWE', 'ENSA')),
  title text not null,
  description text not null default '',
  is_active boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.enrollments (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  enrolled_at timestamptz not null default now(),
  unique (course_id, student_id)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), 'student');
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.current_user_role()
returns public.app_role
language sql
stable
security definer set search_path = ''
as $$
  select role from public.profiles where id = auth.uid();
$$;

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.enrollments enable row level security;

create policy "Users can read their own profile"
on public.profiles for select to authenticated
using (id = auth.uid());

create policy "Users can update their own name"
on public.profiles for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "Authenticated users can read active courses"
on public.courses for select to authenticated
using (is_active = true or public.current_user_role() in ('instructor', 'admin'));

create policy "Instructors can create courses"
on public.courses for insert to authenticated
with check (public.current_user_role() in ('instructor', 'admin'));

create policy "Instructors can update courses"
on public.courses for update to authenticated
using (public.current_user_role() in ('instructor', 'admin'))
with check (public.current_user_role() in ('instructor', 'admin'));

create policy "Students can read their enrollments"
on public.enrollments for select to authenticated
using (student_id = auth.uid() or public.current_user_role() in ('instructor', 'admin'));

create policy "Instructors can manage enrollments"
on public.enrollments for all to authenticated
using (public.current_user_role() in ('instructor', 'admin'))
with check (public.current_user_role() in ('instructor', 'admin'));

insert into public.courses (code, title, description) values
('ITN', 'Introduction to Networks', 'Network fundamentals, Ethernet, IP addressing, and basic configuration.'),
('SRWE', 'Switching, Routing, and Wireless Essentials', 'VLANs, switching, routing, WLANs, and LAN security.'),
('ENSA', 'Enterprise Networking, Security, and Automation', 'OSPF, ACLs, NAT, security, management, and automation.');
